--- #YAML:1.0
name:               Chess-PGN-Filter
version:            0.15
abstract:           Perl extension for converting PGN files to other formats.
author:
    - Hugh S. Myers <hsmyers@sdragons.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Chess::PGN::EPD:    0.08
    Chess::PGN::Parse:  0.01
    Test:               1.15
    Text::DelimMatch:   1.01
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
